/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProyectoFrame;

import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class frm_ingreso extends javax.swing.JFrame {

    /**
     * Creates new form frm_ingreso
     */
    public frm_ingreso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dkp_login = new javax.swing.JDesktopPane();
        pnl_login = new javax.swing.JPanel();
        btn_verificar = new javax.swing.JButton();
        jtf_usuario = new javax.swing.JTextField();
        jpf_contraseña = new javax.swing.JPasswordField();
        jl_mail = new javax.swing.JLabel();
        jl_contraseña = new javax.swing.JLabel();
        jl_inicio_de_sesion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_ocultar = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMaximumSize(new java.awt.Dimension(600, 350));
        setMinimumSize(new java.awt.Dimension(600, 350));
        setName("Login"); // NOI18N
        setResizable(false);

        dkp_login.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnl_login.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_verificar.setIcon(new javax.swing.ImageIcon("C:\\Users\\lusai\\OneDrive\\Documentos\\ULP\\1º Año - Segundo Semestre\\Laboratorio de Progrmación I\\Prueba_TP3\\Icons\\icons8-cliente-windows-48.png")); // NOI18N
        btn_verificar.setText("Registrar");
        btn_verificar.setAlignmentX(0.5F);
        btn_verificar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_verificar.setName("btn_verificar"); // NOI18N
        btn_verificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verificarActionPerformed(evt);
            }
        });

        jtf_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_usuarioActionPerformed(evt);
            }
        });

        jpf_contraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpf_contraseñaActionPerformed(evt);
            }
        });

        jl_mail.setText("Mail:");
        jl_mail.setAlignmentX(0.5F);
        jl_mail.setFocusable(false);
        jl_mail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jl_contraseña.setText("Contraseña:");
        jl_contraseña.setAlignmentX(0.5F);

        jl_inicio_de_sesion.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jl_inicio_de_sesion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_inicio_de_sesion.setText("Inicio de sesion");
        jl_inicio_de_sesion.setToolTipText("");
        jl_inicio_de_sesion.setAlignmentX(0.5F);

        javax.swing.GroupLayout pnl_loginLayout = new javax.swing.GroupLayout(pnl_login);
        pnl_login.setLayout(pnl_loginLayout);
        pnl_loginLayout.setHorizontalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addContainerGap(114, Short.MAX_VALUE)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_inicio_de_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl_loginLayout.createSequentialGroup()
                        .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_mail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_contraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(114, 114, 114))
            .addGroup(pnl_loginLayout.createSequentialGroup()
                .addGap(184, 184, 184)
                .addComponent(btn_verificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_loginLayout.setVerticalGroup(
            pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_inicio_de_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_mail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(pnl_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jpf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btn_verificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btn_ocultar.setIcon(new javax.swing.ImageIcon("C:\\Users\\lusai\\OneDrive\\Documentos\\ULP\\1º Año - Segundo Semestre\\Laboratorio de Progrmación I\\Prueba_TP3\\Icons\\icons7-ocultar-contraseña-50.png")); // NOI18N
        btn_ocultar.setText("Ocultar");
        btn_ocultar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btn_ocultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ocultarActionPerformed(evt);
            }
        });

        btn_ver.setIcon(new javax.swing.ImageIcon("C:\\Users\\lusai\\OneDrive\\Documentos\\ULP\\1º Año - Segundo Semestre\\Laboratorio de Progrmación I\\Prueba_TP3\\Icons\\icons7-mostrar-contraseña-50.png")); // NOI18N
        btn_ver.setText("Ver");
        btn_ver.setMaximumSize(new java.awt.Dimension(123, 57));
        btn_ver.setMinimumSize(new java.awt.Dimension(123, 57));
        btn_ver.setPreferredSize(new java.awt.Dimension(123, 57));
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(btn_ocultar)
                .addGap(28, 28, 28)
                .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_ver, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .addComponent(btn_ocultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        dkp_login.setLayer(pnl_login, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dkp_login.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dkp_loginLayout = new javax.swing.GroupLayout(dkp_login);
        dkp_login.setLayout(dkp_loginLayout);
        dkp_loginLayout.setHorizontalGroup(
            dkp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkp_loginLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(dkp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        dkp_loginLayout.setVerticalGroup(
            dkp_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dkp_loginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pnl_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dkp_login)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dkp_login)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_verificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verificarActionPerformed
        String usuarioCorrecto = "alumno@ulp.edu.ar";
        String contrasena = "12345678";

        if (jtf_usuario.getText().equalsIgnoreCase(usuarioCorrecto) && jpf_contraseña.getText().equalsIgnoreCase(contrasena)) {
            JOptionPane.showMessageDialog(rootPane, "Bienvenido de nuevo, alumno!");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuario incorrecto");
        }
    }//GEN-LAST:event_btn_verificarActionPerformed

    private void jpf_contraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpf_contraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpf_contraseñaActionPerformed

    private void jtf_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_usuarioActionPerformed

    private void btn_ocultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ocultarActionPerformed
        jpf_contraseña.setEchoChar('*');
    }//GEN-LAST:event_btn_ocultarActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        jpf_contraseña.setEchoChar((char)0);
    }//GEN-LAST:event_btn_verActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_ingreso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_ingreso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ocultar;
    private javax.swing.JButton btn_ver;
    private javax.swing.JButton btn_verificar;
    private javax.swing.JDesktopPane dkp_login;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jl_contraseña;
    private javax.swing.JLabel jl_inicio_de_sesion;
    private javax.swing.JLabel jl_mail;
    private javax.swing.JPasswordField jpf_contraseña;
    private javax.swing.JTextField jtf_usuario;
    private javax.swing.JPanel pnl_login;
    // End of variables declaration//GEN-END:variables
}
